services:
  - type: web
    name: voltaren-backend
    runtime: python
    rootDir: Voltaren-backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn App.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: HALEON_CONTACTO
        sync: false
      - key: GOOGLE_OAUTH_CREDENTIALS
        sync: false
      - key: GOOGLE_TOKEN_JSON
        sync: false